// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNwKQjtMNa2XZ43GuoQXU5yyrte2GOc5I',
    appId: '1:1053059319205:web:64dc97f1350b8349bc944c',
    messagingSenderId: '1053059319205',
    projectId: 'chat-f-project',
    authDomain: 'chat-f-project.firebaseapp.com',
    storageBucket: 'chat-f-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuFeLfcF0EgQ8kwnFyG4om8kNljHnB8L4',
    appId: '1:1053059319205:android:dc9d306b3e8fbee3bc944c',
    messagingSenderId: '1053059319205',
    projectId: 'chat-f-project',
    storageBucket: 'chat-f-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZniLH9DB6a-pdcwGPY87jdDM4U_pVwsQ',
    appId: '1:1053059319205:ios:f991f8ec827dff71bc944c',
    messagingSenderId: '1053059319205',
    projectId: 'chat-f-project',
    storageBucket: 'chat-f-project.appspot.com',
    iosClientId: '1053059319205-bct4i0hk63qno8g87r7d798vp5agm5v7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZniLH9DB6a-pdcwGPY87jdDM4U_pVwsQ',
    appId: '1:1053059319205:ios:6e92c09a899cf2debc944c',
    messagingSenderId: '1053059319205',
    projectId: 'chat-f-project',
    storageBucket: 'chat-f-project.appspot.com',
    iosClientId: '1053059319205-9ohkias7vktro6i4clg1hmh2vmpj5k46.apps.googleusercontent.com',
    iosBundleId: 'com.example.fproject.RunnerTests',
  );
}
